"""Static lexical resources for the rule_v0 controller."""

from __future__ import annotations

import json
import re
from pathlib import Path


STOPWORDS = {
    "a",
    "about",
    "after",
    "all",
    "already",
    "am",
    "an",
    "and",
    "any",
    "are",
    "around",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "for",
    "from",
    "get",
    "go",
    "had",
    "has",
    "have",
    "help",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "just",
    "last",
    "likely",
    "make",
    "me",
    "most",
    "my",
    "nearby",
    "next",
    "no",
    "not",
    "now",
    "of",
    "on",
    "or",
    "our",
    "out",
    "plan",
    "please",
    "right",
    "should",
    "so",
    "still",
    "suggest",
    "than",
    "that",
    "the",
    "their",
    "them",
    "then",
    "there",
    "these",
    "they",
    "this",
    "to",
    "tomorrow",
    "tonight",
    "two",
    "up",
    "use",
    "what",
    "when",
    "which",
    "who",
    "why",
    "with",
    "would",
    "write",
    "you",
    "your",
}

GENERIC_VALUE_TOKENS = {
    "already",
    "also",
    "book",
    "booked",
    "booking",
    "dialogue",
    "did",
    "finally",
    "follow",
    "got",
    "mention",
    "mentioned",
    "month",
    "morning",
    "new",
    "night",
    "paper",
    "plan",
    "recent",
    "reply",
    "sent",
    "still",
    "summer",
    "team",
    "term",
    "trip",
    "turn",
    "user",
    "want",
    "wants",
    "went",
    "week",
    "weeks",
    "year",
    "yesterday",
}

TEMPORAL_HINTS = {
    "am",
    "pm",
    "today",
    "tomorrow",
    "yesterday",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "month",
    "week",
    "quarter",
    "morning",
    "evening",
    "afternoon",
}

UPDATE_MARKERS = {
    "canceled",
    "cancelled",
    "changed",
    "current",
    "currently",
    "dropped",
    "finally",
    "forget",
    "formerly",
    "moved",
    "new",
    "no",
    "instead",
    "now",
    "quit",
    "returned",
    "started",
    "stopped",
    "switched",
    "update",
    "updated",
    "used",
}

NEGATION_PATTERNS = (
    "no longer",
    "not",
    "never",
    "still needs",
    "still pending",
)

PREFERENCE_MARKERS = {
    "concise",
    "dance",
    "enjoy",
    "enjoys",
    "favorite",
    "favourite",
    "likes",
    "love",
    "oat",
    "prefer",
    "prefers",
    "professional",
    "quiet",
    "spicy",
    "upbeat",
    "usually",
    "warm",
}

PREFERENCE_PATTERNS = (
    "would love",
    "i d love",
    "i love",
    "i enjoy",
    "i prefer",
    "trying to learn more",
    "want to learn more",
)

QUERY_INTENT_TOKENS = {
    "advice",
    "better",
    "chat",
    "checking",
    "getting",
    "happening",
    "helpful",
    "interesting",
    "learn",
    "more",
    "name",
    "many",
    "planning",
    "previous",
    "recommend",
    "recommended",
    "remind",
    "remember",
    "resources",
    "results",
    "revisit",
    "some",
    "talked",
    "time",
    "tips",
    "useful",
    "was",
    "we",
    "where",
    "wondering",
    "start",
    "using",
}

BROAD_QUERY_FOCUS_TOKENS = {
    "app",
    "apps",
    "place",
    "places",
    "recipe",
    "recipes",
    "resource",
    "resources",
    "restaurant",
    "restaurants",
    "shop",
    "shops",
    "tool",
    "tools",
    "website",
    "websites",
}

ADVICE_QUERY_PATTERNS = (
    "any advice",
    "any tips",
    "tips on",
    "advice on",
    "better results",
)

SENSITIVE_PATTERNS = (
    "breakup",
    "panic attack",
    "layoff",
    "fertility",
    "inheritance",
    "divorce",
    "depressive episode",
    "debt collection",
    "grieving",
    "funeral",
    "argued",
    "difficult breakup",
    "failed a class",
)

PERSONAL_LIFE_TOKENS = {
    "brother",
    "coworker",
    "debt",
    "divorce",
    "funeral",
    "layoff",
    "parents",
    "professor",
    "relationship",
    "sister",
}

QUERY_PERSONALIZATION_PATTERNS = (
    "can you suggest",
    "can you help me",
    "what should i",
    "which seat should i choose",
    "what coffee order should i get",
    "what birthday gift should i get",
    "can you make me",
    "recruiter follow-up",
    "thank-you note",
)

WRITING_HELP_PATTERNS = (
    "draft",
    "follow up",
    "thank you note",
    "thank-you note",
    "write",
    "wording",
    "email tone",
    "note to",
)

CURRENT_STATE_QUERY_PATTERNS = (
    "current",
    "currently",
    "right now",
    "still",
    "these days",
    "now",
    "no longer",
    "asked you to forget",
    "should now be ignored",
    "ignored in future",
)

_CONCEPT_SPECS_PATH = Path(__file__).resolve().parent.parent / "configs" / "concept_specs.json"


def _load_concept_specs() -> dict[str, dict[str, list[str]]]:
    """Load dataset-specific concept specs from configs/concept_specs.json."""
    return json.loads(_CONCEPT_SPECS_PATH.read_text(encoding="utf-8"))


CONCEPT_SPECS: dict[str, dict[str, list[str]]] = _load_concept_specs()

TOKEN_RE = re.compile(r"[a-z0-9]+")
DATE_RE = re.compile(r"\b(\d{4})[-/](\d{2})(?:[-/](\d{2}))?\b")
TIME_RE = re.compile(r"\b\d{1,2}\s?(?:am|pm)\b")
