"""Static lexical resources for the rule_v0 controller."""

from __future__ import annotations

import re


STOPWORDS = {
    "a",
    "about",
    "after",
    "all",
    "already",
    "am",
    "an",
    "and",
    "any",
    "are",
    "around",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "for",
    "from",
    "get",
    "go",
    "had",
    "has",
    "have",
    "help",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "just",
    "last",
    "likely",
    "make",
    "me",
    "most",
    "my",
    "nearby",
    "next",
    "no",
    "not",
    "now",
    "of",
    "on",
    "or",
    "our",
    "out",
    "plan",
    "please",
    "right",
    "should",
    "so",
    "still",
    "suggest",
    "than",
    "that",
    "the",
    "their",
    "them",
    "then",
    "there",
    "these",
    "they",
    "this",
    "to",
    "tomorrow",
    "tonight",
    "two",
    "up",
    "use",
    "what",
    "when",
    "which",
    "who",
    "why",
    "with",
    "would",
    "write",
    "you",
    "your",
}

GENERIC_VALUE_TOKENS = {
    "already",
    "also",
    "book",
    "booked",
    "booking",
    "dialogue",
    "did",
    "finally",
    "follow",
    "got",
    "mention",
    "mentioned",
    "month",
    "morning",
    "new",
    "night",
    "paper",
    "plan",
    "recent",
    "reply",
    "sent",
    "still",
    "summer",
    "team",
    "term",
    "trip",
    "turn",
    "user",
    "want",
    "wants",
    "went",
    "week",
    "weeks",
    "year",
    "yesterday",
}

TEMPORAL_HINTS = {
    "am",
    "pm",
    "today",
    "tomorrow",
    "yesterday",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "month",
    "week",
    "quarter",
    "morning",
    "evening",
    "afternoon",
}

UPDATE_MARKERS = {
    "canceled",
    "cancelled",
    "changed",
    "current",
    "currently",
    "dropped",
    "finally",
    "forget",
    "formerly",
    "moved",
    "new",
    "no",
    "instead",
    "now",
    "quit",
    "returned",
    "started",
    "stopped",
    "switched",
    "update",
    "updated",
    "used",
}

NEGATION_PATTERNS = (
    "no longer",
    "not",
    "never",
    "still needs",
    "still pending",
)

PREFERENCE_MARKERS = {
    "concise",
    "dance",
    "enjoy",
    "enjoys",
    "favorite",
    "favourite",
    "likes",
    "love",
    "oat",
    "prefer",
    "prefers",
    "professional",
    "quiet",
    "spicy",
    "upbeat",
    "usually",
    "warm",
}

PREFERENCE_PATTERNS = (
    "would love",
    "i d love",
    "i love",
    "i enjoy",
    "i prefer",
    "trying to learn more",
    "want to learn more",
)

QUERY_INTENT_TOKENS = {
    "advice",
    "better",
    "chat",
    "checking",
    "getting",
    "happening",
    "helpful",
    "interesting",
    "learn",
    "more",
    "name",
    "many",
    "planning",
    "previous",
    "recommend",
    "recommended",
    "remind",
    "remember",
    "resources",
    "results",
    "revisit",
    "some",
    "talked",
    "time",
    "tips",
    "useful",
    "was",
    "we",
    "where",
    "wondering",
    "start",
    "using",
}

BROAD_QUERY_FOCUS_TOKENS = {
    "app",
    "apps",
    "place",
    "places",
    "recipe",
    "recipes",
    "resource",
    "resources",
    "restaurant",
    "restaurants",
    "shop",
    "shops",
    "tool",
    "tools",
    "website",
    "websites",
}

ADVICE_QUERY_PATTERNS = (
    "any advice",
    "any tips",
    "tips on",
    "advice on",
    "better results",
)

SENSITIVE_PATTERNS = (
    "breakup",
    "panic attack",
    "layoff",
    "fertility",
    "inheritance",
    "divorce",
    "depressive episode",
    "debt collection",
    "grieving",
    "funeral",
    "argued",
    "difficult breakup",
    "failed a class",
)

PERSONAL_LIFE_TOKENS = {
    "brother",
    "coworker",
    "debt",
    "divorce",
    "funeral",
    "layoff",
    "parents",
    "professor",
    "relationship",
    "sister",
}

QUERY_PERSONALIZATION_PATTERNS = (
    "can you suggest",
    "can you help me",
    "what should i",
    "which seat should i choose",
    "what coffee order should i get",
    "what birthday gift should i get",
    "can you make me",
    "recruiter follow-up",
    "thank-you note",
)

WRITING_HELP_PATTERNS = (
    "draft",
    "follow up",
    "thank you note",
    "thank-you note",
    "write",
    "wording",
    "email tone",
    "note to",
)

CURRENT_STATE_QUERY_PATTERNS = (
    "current",
    "currently",
    "right now",
    "still",
    "these days",
    "now",
    "no longer",
    "asked you to forget",
    "should now be ignored",
    "ignored in future",
)

CONCEPT_SPECS: dict[str, dict[str, list[str]]] = {
    "support_group_event": {
        "patterns": ["lgbtq", "support group", "conference", "pride parade"],
        "answer_markers": ["support group"],
    },
    "summer_research": {
        "patterns": ["research", "researching", "adoption agencies", "start a family"],
        "answer_markers": ["research", "researching", "adoption agencies"],
    },
    "charity_awareness": {
        "patterns": ["charity race", "awareness", "mental health"],
        "answer_markers": ["mental health", "awareness"],
    },
    "classic_books": {
        "patterns": ["classic", "childrens books", "books"],
        "answer_markers": ["classic", "books"],
    },
    "job_loss": {
        "patterns": ["banker", "job", "lose", "lost"],
        "answer_markers": ["banker", "job", "lost"],
    },
    "car_donation": {
        "patterns": ["donate", "donated", "old car", "car"],
        "answer_markers": ["donate", "donated", "old car"],
    },
    "screenplay_completion": {
        "patterns": ["screenplay", "finished", "finish", "first screenplay"],
        "answer_markers": ["screenplay", "finished", "finish"],
    },
    "ankle_injury": {
        "patterns": ["ankle", "injury", "sprain", "sprained"],
        "answer_markers": ["ankle", "injury", "sprained"],
    },
    "diet": {
        "patterns": ["diet", "vegetarian", "pescatarian", "vegan", "fish", "tofu"],
        "answer_markers": ["vegetarian", "pescatarian", "vegan", "fish"],
    },
    "airport_choice": {
        "patterns": ["airport", "ohare", "midway", "flight", "flights"],
        "answer_markers": ["airport", "ohare", "midway"],
    },
    "meeting_schedule": {
        "patterns": ["product sync", "sync", "tuesday", "wednesday", "pm", "quarter"],
        "answer_markers": ["product sync", "sync", "tuesday", "wednesday", "pm"],
    },
    "laptop_device": {
        "patterns": ["laptop", "charger", "macbook", "thinkpad", "usb c", "hub"],
        "answer_markers": ["laptop", "charger", "macbook", "thinkpad"],
    },
    "residence": {
        "patterns": ["city", "live", "lives", "moved", "austin", "chicago"],
        "answer_markers": ["live", "lives", "moved", "austin", "chicago"],
    },
    "class_course": {
        "patterns": [
            "class",
            "course",
            "summer",
            "data mining",
            "distributed systems",
            "enrolled",
            "switched",
        ],
        "answer_markers": [
            "class",
            "course",
            "data mining",
            "distributed systems",
            "enrolled",
            "switched",
        ],
    },
    "major": {
        "patterns": ["major", "biology", "psychology", "medical school"],
        "answer_markers": ["major", "biology", "psychology"],
    },
    "dog_food": {
        "patterns": ["dog food", "dog", "formula", "salmon", "chicken", "pet store"],
        "answer_markers": ["dog food", "formula", "salmon", "chicken"],
    },
    "hotel_booking": {
        "patterns": ["hotel", "conference", "harbor hotel", "riverfront suites", "booked"],
        "answer_markers": ["hotel", "harbor", "riverfront", "suites", "booked"],
    },
    "invoice_status": {
        "patterns": ["invoice", "sent", "send", "pending", "reply", "follow up"],
        "answer_markers": ["invoice", "sent", "pending", "send"],
    },
    "work_schedule": {
        "patterns": ["weekend", "weekends", "weekday", "weekdays", "shifts", "coverage", "role"],
        "answer_markers": ["weekend", "weekends", "weekday", "weekdays", "shifts"],
    },
    "museum_tickets": {
        "patterns": ["museum", "tickets", "ticket", "sister", "two beds"],
        "answer_markers": ["museum", "tickets", "ticket", "sister"],
    },
    "gym_membership": {
        "patterns": ["gym", "membership", "lakeside", "north loop", "spin class", "joined"],
        "answer_markers": ["gym", "membership", "lakeside", "north loop", "joined"],
    },
    "pet_trip": {
        "patterns": ["dog", "trip", "pet friendly", "travel bowl", "parents"],
        "answer_markers": ["dog", "pet friendly", "travel bowl", "parents"],
    },
    "paper_submission": {
        "patterns": ["paper", "draft", "submit", "submission", "professor", "edit"],
        "answer_markers": ["paper", "draft", "submit", "submission"],
    },
    "food_choice": {
        "patterns": ["lunch", "spicy noodles", "coffee", "oat milk", "dessert"],
        "answer_markers": ["lunch", "spicy noodles", "coffee", "oat milk", "dessert"],
    },
    "writing_style": {
        "patterns": [
            "recruiter",
            "follow up",
            "email tone",
            "professional",
            "concise",
            "thank you note",
            "wording",
        ],
        "answer_markers": [
            "recruiter",
            "follow up",
            "email tone",
            "professional",
            "concise",
            "wording",
        ],
    },
    "gift_choice": {
        "patterns": ["birthday gift", "coworker", "tea", "mugs", "mug"],
        "answer_markers": ["gift", "coworker", "tea", "mugs", "mug"],
    },
    "workout_music": {
        "patterns": ["workout", "playlist", "upbeat", "pop", "dance", "tracks"],
        "answer_markers": ["workout", "playlist", "upbeat", "pop", "dance"],
    },
    "rainy_activities": {
        "patterns": ["rainy", "weekend", "art museums", "quiet cafes", "museums", "cafes"],
        "answer_markers": ["rainy", "weekend", "museums", "cafes"],
    },
    "flight_seat": {
        "patterns": ["seat", "aisle", "flight", "long flights"],
        "answer_markers": ["seat", "aisle", "flight"],
    },
}

TOKEN_RE = re.compile(r"[a-z0-9]+")
DATE_RE = re.compile(r"\b(\d{4})[-/](\d{2})(?:[-/](\d{2}))?\b")
TIME_RE = re.compile(r"\b\d{1,2}\s?(?:am|pm)\b")
